[[section-architecture-constraints]]
== Restricciones de arquitectura

.Restricciones técnicas
[options = "header", cols = "1,2"]
|===
 Restricción | Descripción |
 *https://solidproject.org/[_SoLiD_]* |
    El uso de SoLiD nos implica que sea una aplicación descentralizada teniendo que tener hacer uso de los POD. |
 *https://github.com/[GitHub]* |
    Nuestro proyecto originalmente está alojado en esta plataforma. |
 *Uso exclusivo desde el móvil* |
	Es obligatorio que se desarrolle una aplicación móvil para acceder a la aplicación. |
 *https://arc42.org/[Arc42]* |
    Es requisito recomendado su uso para la documentación. |
 *Tests* |
    Uso obligatorio de pruebas unitarias para probar el buen funcionamiento. |
|===

.Restricciones de organizacíon
[options = "header", cols = "1,2"]
|===
 Restricción | Descripción |
 *Tiempo* |
    El desarrollo de todo el proyecto esta limitado, sólo disponemos de lo que dure el cuatrimestre. |
 *Miembros* |
    Nuestra condición de estudiantes universitarios nos impide dedicarnos completamente al proyecto RadarIn, ya que, además de a este proyecto, debemos prestar parte de nuestro tiempo a otras asignaturas. |
 *Entregas* |
    Hay entregas previas a la finalizacion del proyecto, con lo cual es necesario trabajar de forma constante sobre el proyecto. |
|===

.Restricciones politicas
[options = "header", cols = "1,2"]
|===
 Restricción | Descripción |
 *https://ayudaleyprotecciondatos.es/lopdgdd/[Ley Orgánica de Protección de Datos y Garantía de los Derechos Digitales (LOPDGDD)]* |
   A nivel de cumplimiento de las regulaciones españolas, debemos cumplir la ley que regula el tratamiento de datos de carácter personal en España. |
 *https://gdpr.eu/[Reglamento General de Protección de Datos (RGPD)]* |
   A nivel de país miembro de la Unión Europea, debemos cumplir el reglamento europeo relativo a la protección de las personas físicas en lo que respecta al tratamiento de sus datos personales y a la libre circulación de estos datos. |
|===
