[[section-deployment-view]]

== Perspectiva de despliegue

.Contexto
RadarIn, nuestra aplicación, está orientada a usuarios personales y será desplegada en navegador, aunque esta sea distribuida principalmente en dispositivos móviles.
Concretamente, serán Microsoft Edge y Google Chrome los dos navegadores de referencia, ambos basados en https://www.chromium.org/[Chromium].

.Tecnologías
Los datos del usuario serán almacenados en un https://solidproject.org/users/get-a-pod[POD], siguiendo así las especificaciones del proyecto https://solidproject.org/[SoLiD].
Toda característica de la aplicación dependerá de su homóloga en la plataforma https://www.heroku.com/[Heroku], donde hemos decidido que sea desplegada.

=== Infraestructura

Siguiendo el patrón de diseño de n capas, hemos distribuido el código en tres capas:

* *Capa de interfaz de usuario*. Hemos desarrollado la interfaz de usuario como un conjunto de componentes de React.
* *Capa de lógica de negocio*. Para el desarrollo de las operaciones comunes en la aplicación.
* *Capa de persistencia*. Se encuentra alojada en una API REST desplegada con MongoDB.

.Sistemas implicados en la infraestructura.
- *Dispositivos de usuario*. Un dispositivo móvil.
- *Dispositivo de administrador*. Puede ser un dispositivo móvil o un dispositivo de sobremesa.
- *Heroku*. Sirve de plataforma a la aplicación RadarIn.
- *POD de SoLiD*. Almacena la información del usuario en un servidor de terceros, cuyo almacenamiento tiene que haber sido llevado a cabo por el usuario previamente.

[plantuml, deployment_view1, svg]
----
database "SoLiD" {
  [POD de Usuario]
}

node "RadarIn (Heroku)" {
  package "WebApp" {
    [View] <-> [Service]
    [Service] <-> [API WebApp]
  }
  package "RestApi" {
    [API RestApi]
  }
  [API WebApp] <-> [API RestApi]
  database "MongoDB" {
    [Ubicaciones]
    [Peticiones de amistad]
  }
  [API RestApi] <-> [Ubicaciones]
  [API RestApi] <-> [Peticiones de amistad]
}

Usuario  <-> [View]
[Service] <-> [POD de Usuario]
----

[.text-right]
Figura 7.1. Perspectiva de despliegue.
