[[section-concepts]]
== Conceptos transversales

=== Conceptos del dominio

.Los conceptios del dominio son los siguientes:
- *Usuario*. Es la persona que usa la aplicación. El sistema almacenará su localización en un instante de tiempo, no almacenará ningún tipo de información que no sea necesaria.
- *Administrador*. Es la persona que usa la aplicación. El sistema almacenará su localización en un instante de tiempo, no almacenará ningún tipo de información que no sea necesaria.
- *Pod*. Es un repositorio de usuarios que almacenará la información que no se considera mínima del usuario, por ejemplo sus amigos. Sigue las especificaciones SoLiD y puede almacenarse en cualquier plataforma. Es el propio usuario el que tiene gestón total de su información.
- *Amigo*. Un usuario tendrá amigos y le informará (mediante notificaciones) cuando uno de ellos esté cerca.

=== Patrones de arquitectura
Basamos nuestra aplicación en el patrón n capas, consiste en separar los datos y la lógica de negocio de la aplicación de la representación visual y los canales de comunicación. Este patrón de arquitectura de software se basa en las ideas de reutilización de código y la separación de conceptos, características que buscan facilitar la tarea de desarrollo de aplicaciones y su posterior mantenimiento.

=== Experiencia de usuario
==== Diseño de la interfaz de usuario
La idea de la interfaz es hacerla intuitiva y dirigida para todos los tipos de usuarios. Además buscamos hacerla limpia y bonita estéticamente.

==== Internacionalización
La idea primera del desarrollo de la aplicación es hacerla en español, ya que es nuestro idioma materno y nos sentimos más comodos para desarrollar la aplicación y la documentación.

=== Seguridad
Se considera una aplicación segura gracias al uso del protocolo https://es.wikipedia.org/wiki/Protocolo_seguro_de_transferencia_de_hipertexto[HTTPS]. 
Además, gracias a los PODS los datos del usuario se almacenarán de una forma privada y es el propio usuario el que tiene que dar acceso a estos datos.

=== Desarrollo
==== Construcción
Respecto a este apartado usaremos la libreria https://es.reactjs.org/[React] para lograr los objetivos en cuanto a funcionalidad que deseamos.
https://es.reactjs.org/[React] es una biblioteca de JavaScript de código abierto diseñada para crear interfaces de usuario con el objetivo de facilitar el desarrollo de aplicaciones en una sola página. Es mantenido por Facebook y la comunidad de software libre. En el proyecto hay más de mil desarrolladores libres.

Intenta ayudar a los desarrolladores a construir aplicaciones que usan datos que cambian todo el tiempo. Su objetivo es ser sencillo, declarativo y fácil de combinar. https://es.reactjs.org/[React] sólo maneja la interfaz de usuario en una aplicación; https://es.reactjs.org/[React] actuará como la capa más superior en un contexto en el que se use el patrón por capas.

==== APIs
Usaremos una API de mapas para mostrar un mapa al usuario. Usaremos https://wiki.openstreetmap.org/wiki/Main_Page[OpenStreetMap], una API de edición para extraer y guardar geoinformación en el mapa. En concreto, utilizaremos la librería https://leafletjs.com/[Leaflet] para realizar operaciones sobre el mapa.

También utilizaremos una o más APIs para crear llamadas remotas entre los servicios WebApp y RestApi.

==== Migración
Desarrollaremos una aplicación Web para móviles. Aunque también podrá ser utilizada en equipos de sobremesa, su principal plataforma serán los dispositivos smartphone.

=== Recuperación ante un imprevisto
La información alojada en los PODs gozará de una disponibilidad y una persistencia que no dependerá de la aplicación, sino del proveedor del POD.
En cambio, la información alojada en la propia base de datos MongoDB, dependerá directamente del entorno de despliegue, en este caso Heroku.

=== Pruebas
Hemos acordado realizar pruebas exhaustivas, de aceptación y de carga cuando la aplicación esté en funcionamiento.




